### ISSUE TITLE
Moving files using 'M' key binding stopped working

### ISSUE THREAD

**Issue by ignacysokolowski** [aziz/SublimeFileBrowser#101]
Hey,

I used to move files to different locations using `M` key binding. Since commit 0d8ec949fadb4b48df358c147c8afee7798da1bd it is no longer possible.

Is there any other way to move a file?

**Comment by aziz** [comment]
Use your OS default shortcuts.

https://github.com/aziz/SublimeFileBrowser#cut-copy-and-paste-files

**Comment by ignacysokolowski** [comment]
I've seen them but I thought there's still a way to move without changing directory.
Before, it asked me where to move and I could type the destination.

**Comment by aziz** [comment]
I can see your point and I personally like typing the address most of the time. 
The cut/copy/paste feature was implemented by @vovkkk. Let's see if he agrees bringing back the Move command with an address bar a pro feature.

**Comment by ignacysokolowski** [comment]
OK, thanks for help! :)

**Comment by vovkkk** [comment]
I do not disagree, but won’t do this (at least in foreseeable future, i.e. probably not this year).

Note, that you can open several FB tabs and cut in one, then paste at any other.
Also, you can press <kbd>g</kbd> type path, for that matter I thought about ‘go back’ feature, which I’ll probably do in this year (not sure).

**Comment by vovkkk** [comment]
Add it in [separate branch](https://github.com/aziz/SublimeFileBrowser/tree/prompt-fo), please test and tell me if any problems appear. 
<kbd>⌘+shift+v</kbd> or <kbd>ctrl+shift+v</kbd> to open prompt.

I’m going to realise it with some other fixes on this weekend or next one.
