### ISSUE TITLE
I know, this is not a real bug, but ...

### ISSUE THREAD

**Issue by mkastner** [aziz/SublimeFileBrowser#103]
... I am missing in the documentation an explanation how to move back and forth between file browser and file.

**Comment by vovkkk** [comment]
Just like you move between regular tabs; or focus group (look at main menu View); or Go to Anything (main menu Goto); or single_pane:true argument for keybinding (look at readme).









От: mtkastner
Отправлено: ‎пятница‎, ‎11‎ ‎декабря‎ ‎2015‎ г. ‎13‎:‎43
Кому: aziz/SublimeFileBrowser





I am missing in the documentation an explanation how to move back and forth between file browser and file

**Comment by mkastner** [comment]
No, I mean when the browser is in left or right pane mode.

**Comment by vovkkk** [comment]
It is always just a tab.
You can focus left group with <kbd>ctrl+1</kbd> and right group with <kbd>ctrl+2</kbd> on Windows; 
for other OS look at `View` → `Focus Group`
