### ISSUE TITLE
"dired_index" is empty

### ISSUE THREAD

**Issue by laggingreflex** [aziz/SublimeFileBrowser#104]
Getting this error a lot:

    "dired_index" is empty
    that shouldn't happen ever, there is some bug

It's happened a lot of times in the past week or so that I've started using this plugin. 
I can't pin point a pattern for exactly when or why it happens.

Here's the output from the console panel:

    error: FileBrowser:

    "dired_index" is empty,
    that shouldn’t happen ever, there is some bug.
    Traceback (most recent call last):
      File "dired_misc in C:\…\Sublime Text 3\Installed Packages\FileBrowser.sublime-package", line 311, in watch_threads
      File "dired_misc in C:\…\Sublime Text 3\Installed Packages\FileBrowser.sublime-package", line 374, in vcs_colorized
    TypeError: zip argument #1 must support iteration

I'm using these settings currently, but I think the error happened when I was only using the defaults as well.

    "dired_confirm_send2trash": false,
    "dired_hijack_new_window": "dired",
    "dired_width": 0.2,
    "tab_size": 1,      

Using it on Sublime 3 (3083) on Windows 10.

**Comment by vovkkk** [comment]
dired_index is a representation of items in a view, where first item of index is first line of view, second is second line, etc. If line is directory or file then in index it is represented as full path, e.g.
`['⠤', 'C:\\Users\\vova\\.designer\\', 'C:\\Users\\vova\\.gstreamer-0.10\\', ...`

dired_index is created/modified during refresh and expand/collapse.

So it may be empty 1) before refresh is finished, 2) if some error/exception occured during refresh.
I believe that plugin handle it all right, the latest version was two month ago, I use plugin regulary.

Taking these into account, plus traceback that doesn’t make sense to me in particular context `TypeError: zip argument #1 must support iteration`;
I recommend you, 

1. remove plugin, 
2. exit Sublime Text,
3. install plugin
4. exit Sublime Text

Hopefully, it’ll ‘fix’ the problem; if it won’t, then please come up with certain steps to reproduce the bug.

**Comment by TiMBuS** [comment]
Hello, I have this exact same error whenever I open and close the sidebar quickly. To trigger the issue I only need to press the hotkey twice.

Same console output:
```
"dired_index" is empty,
that shouldn’t happen ever, there is some bug.
Traceback (most recent call last):
  File "dired_misc in /home/user/.config/sublime-text-3/Installed Packages/FileBrowser.sublime-package", line 311, in watch_threads
  File "dired_misc in /home/user/.config/sublime-text-3/Installed Packages/FileBrowser.sublime-package", line 374, in vcs_colorized
TypeError: zip argument #1 must support iteration
```

Hotkey is setup as recommended in the README:
```json
	{
		"keys": ["f2"],
		"command": "dired",
		"args": { "immediate": true, "other_group": "left" }
	}
```

I just mash f2 until the error occurs..

**Comment by vovkkk** [comment]
Thank you @TiMBuS 

> I just mash f2 until the error occurs

It does produce the same bug for me, but only on 3083.

3095 and 2221 work fine though, so it is low priority for now.

**Comment by vovkkk** [comment]
Interesting, that despite updates, this issue is still reproducible in beta (3103), but not reproducible in dev (3104).

I think it happens because VCS thread keep running after the view was closed.

@laggingreflex @TiMBuS could you please check if following patch fix it for you and VCS integration still work? it seems right on my machine, but I’m not sure

```diff
--- dired_misc.py	Thu Feb 18 01:30:05 2016
+++ dired_misc.py	Thu Feb 18 01:30:11 2016
@@ -371,6 +371,8 @@
 
     def vcs_colorized(self, changed_items):
         '''called on main thread'''
+        if not self.view.settings().has('dired_index'):
+            return  # view was closed
         modified, untracked = [], []
         files_regions = dict((f, r) for f, r in zip(self.get_all(), self.view.split_by_newlines(Region(0, self.view.size()))))
         colorblind = self.view.settings().get('vcs_color_blind', False)
```

**Comment by vovkkk** [comment]
Pff, I had vcs disabled in 3104. In fact it is reproducible in any ST3.
