### ISSUE TITLE
Instead of Preview making `space` open the file or another keybinding on OSx

### ISSUE THREAD

**Issue by excetara2** [aziz/SublimeFileBrowser#109]
I was hoping to open in an external program instead of previewing some files in the dired window (for example a .jpg,.mp4, or .pdf. Can you set a keybinding to run the command  `open filename here` or another way if there is a better generic way to open any file on OSx.

Is this possible to add a keybinding to do this?

**Comment by vovkkk** [comment]
It is possible.
Since I cannot test it without OSX, I post diff. Can you test it? does it work?

```diff
--- dired_misc.py Tue Apr 05 12:42:12 2016
+++ dired_misc.py Wed Apr 06 13:57:51 2016
@@ -105,20 +105,22 @@
     """
     quick look current file in mac or open in default app on other OSs
     """
-    def run(self, edit):
+    def run(self, edit, preview=True):
         self.index = self.get_all()
         files = self.get_marked() or self.get_selected(parent=False)
         if not files:
             return sublime.status_message('Nothing chosen')
-        if OSX:
+        if OSX and preview:
             cmd = ["qlmanage", "-p"]
             for filename in files:
                 fqn = join(self.path, filename)
                 cmd.append(fqn)
             subprocess.call(cmd)
         else:
-            if NT:
-                launch = lambda f: os.startfile(f)
+            if OSX:
+                launch = lambda f: subprocess.call(['open', f])
+            elif NT:
+                launch = lambda f: subprocess.call(['start', f], shell=True)
             else:
                 launch = lambda f: subprocess.call(['xdg-open', f])
             for filename in files:
```

```js
  {
    "keys": [" "],
    "command": "dired_quick_look", "args": { "preview": false},
    "context": [
      { "key": "selector", "operator": "equal", "operand": "text.dired" },
      { "key": "setting.dired_rename_mode", "operand": false }
    ]
  }
```

**Comment by excetara2** [comment]
I tried to `git apply` the patch and it says corrupt patch at line 29.

Anyways, I manually entered the lines and it works great so thanks for that.

Also I think a good feature would be if you can open the current folder in the terminal. I know the command that needs to be run on mac but not sure how to get the current folder or the best place to put this in the code.

**Comment by vovkkk** [comment]
> the best place to put this in the code.

`dired_misc.py` is exact place for that kind of stuff, if you’re going to send pull request.



> how to get the current folder

If you inherit new command from BaseCommand (just like all others), then it is simply `self.path`.


There are several fixes pending to be committed and released, I’ve already promised to do that on prev weekend, but yea, this weekend—for sure.
