### ISSUE TITLE
Vintageous disabled only after loosing focus

### ISSUE THREAD

**Issue by asfktz** [aziz/SublimeFileBrowser#110]
seems like only after loosing and restoring focus again, the `__vi_external_disable": true` take action

I use Vintageous, with `__vi_external_disable": true` as it configured in fileBrowser default settings

I've recoded my screen to better explain it:
https://www.youtube.com/watch?v=UVS6dArn9iM

**Comment by vovkkk** [comment]
Hard to fix, sometimes it does not work, seems like there is some issue in Vintagious too, or in ST, race condition or something.

Probably, the best way to fix would be disable Vintagious directly whenever you open FileBrowser using [Chain of Command](https://packagecontrol.io/packages/Chain%20of%20Command).

**Comment by sourcevault** [comment]
> seems like only after loosing and restoring focus again, the `__vi_external_disable": true` take action
> 
> I use Vintageous, with `__vi_external_disable": true` as it configured in fileBrowser default settings
> 
> I've recoded my screen to better explain it: https://www.youtube.com/watch?v=UVS6dArn9iM

it says the video is private, would really love to see it.
