### ISSUE TITLE
Suggesting the possibility of different keymaps for different operating systems?

### ISSUE THREAD

**Issue by excetara2** [aziz/SublimeFileBrowser#113]
Is this possibly a good idea because on mac maybe you don't need `ctrl+c`,`ctrl+x`, and `ctrl+z` and these can interfere with other packages. Specifically I am thinking `sublemacs` because `ctrl+x` and `ctrl+c` can be bound to other commands so at first didn't realize I was cutting and copying files. Anyways just thought I'd see your thoughts.

**Comment by vovkkk** [comment]
Yea, I agree.
It was started with pretty agnostic keys initially, so there was no need for different files; but now it makes sense to encapsulate some of bindings.
