### ISSUE TITLE
How to remove circle that seems to come up in my dired windows. Is it part of the theme?

### ISSUE THREAD

**Issue by excetara2** [aziz/SublimeFileBrowser#116]
The circle can be seen at the bottom of the files here but I don't know why it comes up. I changed my margins today to see if I like it and the circle always appears. Do I need to modify the color_scheme? When I change it it seems to go away but then it comes back eventually after I change it back. Any ideas?

[Link to image here](https://www.dropbox.com/s/62arfabcqx1e5j6/Screenshot%202016-05-20%2020.58.40.png?dl=0)

**Comment by vovkkk** [comment]
Looks like mark: `Edit` → `Mark` → `Clear Mark` while cursor on that line
Perhaps it appear due to keybindings conflict, don’t know really.

BTW, you can drop images right here, in ‘leave comment’ field.

**Comment by excetara2** [comment]
Yes it's the mark from sublemacs didn't realize it and okay will do next time.

Thanks for the help.

**Comment by excetara2** [comment]
Also what does fold_buttons do exactly? Seems it just moves the buffer over to the write in the window.

**Comment by vovkkk** [comment]
Fold buttons are visible when true

![2016-05-20_18-48-39](https://cloud.githubusercontent.com/assets/1975298/15428170/9ffd1c7a-1ebb-11e6-9358-9074af696f78.png)
