### ISSUE TITLE
escape to close browser?

### ISSUE THREAD

**Issue by sammcj** [aziz/SublimeFileBrowser#118]
This may sound like a stupid question, but other than selecting a file and hitting enter to open it, how do you close the file browser?

I would have expected that escape would do it, but no?

**Comment by vovkkk** [comment]
1. It is normal tab, so any default keys will do, e.g. on Windows <kbd>ctrl+w</kbd>

2. If you launch browser with `"other_group"` argument while existing browser is focused it will be closed (the behaviour is supposed to mimic toggle sidebar)

3. You can bind escape in you user keybindings file:

    ```js
    {
        "keys": ["escape"],
        "command": "close_file",
        "context": [
            { "key": "selector", "operator": "equal", "operand": "text.dired" },
            { "key": "setting.dired_rename_mode", "operand": false },
            { "key": "num_selections", "operator": "equal", "operand": 1 },
            { "key": "has_next_field", "operator": "equal", "operand": false },
            { "key": "has_prev_field", "operator": "equal", "operand": false },
            { "key": "panel_visible", "operator": "equal", "operand": false },
            { "key": "overlay_visible", "operator": "equal", "operand": false },
            { "key": "auto_complete_visible", "operator": "equal", "operand": false }
        ]
    }
    ```

**Comment by sammcj** [comment]
Brilliant answer, thank you so much for your time @vovkkk 👍
