### ISSUE TITLE
Auto-update/refresh

### ISSUE THREAD

**Issue by aramk** [aziz/SublimeFileBrowser#119]
It seems that the color added from `git status` doesn't update when changing files? I need to backspace out of the directory and back in for it to take effect?

**Comment by vovkkk** [comment]
Yes, you can press <kbd>r</kbd> to refresh view.

Auto-update should be possible and this issue was raised previously, but the concern is performance, esp. in edge cases.

I think we are going to reach this goal sooner or later, let’s keep it open.

**Comment by aramk** [comment]
Ah ok, sounds good 👍 Pressing r key does work. Perhaps we can limit the git status call to only update for visible files, and when we expand a directory perhaps.

**Comment by vovkkk** [comment]
I’ve publish basic implementation in [autorefresh branch](https://github.com/aziz/SublimeFileBrowser/tree/autorefresh), let’s test it.

Before publish it in master, we have to do following stuff (I hope to finish it in next couple of weeks):
- [ ] fix all bugs, if any (please, report them here)
- [ ] global disable of auto-refresh via user settings
- [ ] per-view disable of auto-refresh via context menu
- [ ] scheduling auto-refresh to prevent it happen more than once per second (or other suitable period of time, I’m not sure yet) — this is needed for good performance when a lot of stuff happens in folder, e.g. some process copy many files into it
- [ ] add compiled fsevent module for watchdog into [sublime-watchdog](https://github.com/vovkkk/sublime-watchdog) — this is needed for better performance on OS X, I’ve no Mac, so it’s up to you Mac-users.
- [ ] make code pretty, refactor, all that jazz

**Comment by vovkkk** [comment]
Any suggestions for ‘icons’ that show if current view is supposed to be automatically refreshed?

For now I take Ѻ and Ӝ
In sync 
![2016-08-11_16-17-35](https://cloud.githubusercontent.com/assets/1975298/17584236/9ed6266a-5fdf-11e6-9818-0aae07b8dfbd.png)
Not in sync 
![2016-08-11_16-17-57](https://cloud.githubusercontent.com/assets/1975298/17584246/a8719632-5fdf-11e6-8da0-7d9887433392.png)

**Comment by aziz** [comment]
These characters look weird. does it need to be on status bar? can't we just log it to the console?

**Comment by vovkkk** [comment]
The reason was that I’ve put `Toggle` in context menu so these chars were supposed to help user understand what will happen, disable or enable.

Now I figured how to change caption on the fly, so no need to use status-bar.

**Comment by vovkkk** [comment]
It seems ready in general, I’m going to release new version this Friday.
