### ISSUE TITLE
Can't install filebrowser via package control

### ISSUE THREAD

**Issue by jakekei** [aziz/SublimeFileBrowser#124]
Hello,

I just have a fresh installation of win 10 professional with all updated (32 bits), and then installed the latest version of sublime text 3 (build 3114, 32 bits).  I installed package control and able to install packages such as StataEditor via it.

However, when I tried to install FileBrowser, nothing happened.  These are what I found in the console:

> ignored packages updated to: ["FileBrowser"]
reloading settings Packages/User/Package Control.sublime-settings
Package Control: The dependency package_events is not currently installed; installing
reloading settings Packages/User/Preferences.sublime-settings
Package Control: The dependency package_events has successfully been installed or updated
Package Control: The dependency pathtools is not currently installed; installing
Package Control: The dependency specified, pathtools, is not available
Package Control: The dependency pathtools could not be installed or updated
ignored packages updated to: []
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings

I wonder did I miss something here?

Best,
Jake

**Comment by vovkkk** [comment]
I’m almost certain it is bug in PC, because https://packagecontrol.io/channel_v3.json does not contain `pathtools` under `"dependencies_cache"` key.

For now we have just deal with it (install [manually](https://github.com/aziz/SublimeFileBrowser#installation)) and wait reply/action from @wbond

**Comment by wbond** [comment]
It'll take a little bit for the data to be refreshed, but here was the fix: https://github.com/wbond/package_control_channel/commit/9ebc01b0c58373ec822ed3128eae1fd7e9439c95

**Comment by vovkkk** [comment]
Nice! Thank you.

BTW, I would assume that absent (for whatever reason) dependency would/should not prevent installation of package, hm.
