### ISSUE TITLE
Preview directory

### ISSUE THREAD

**Issue by vovkkk** [aziz/SublimeFileBrowser#131]
We can show popup with Properties of directory (size, item amounts, dates, list of items since there is scroll so it is not an issue even if there are many ones or we can limit to some amount like 20 or 50 or 100).

I’ve created issue as reminder for myself (want to do it in this year) and to check if there are any objections or amendments.

**Comment by aziz** [comment]
This is Awesome, something I always wanted. I don't think any other plugin can do such a thing in sublime. :+1:

**Comment by aziz** [comment]
Here are some suggestions to make it event better: 

1. Show same info box for files as well. with information like `permissions` `mofied/created dates` and `size` we can even add some action button to preview them in explorer or open in external app

2. Let's user the new `on_hover` api from sublime to show this dialog when you hover with mouse over a file or directory. 

3. Let's document this amazing feature in Readme with screenshots and update shortcuts window

**Comment by vovkkk** [comment]
Alright, good ideas. I’ll look into it in this/next week.

But I kinda afraid to use on hover, because like I mentioned in release note it might consume too much RAM, and CPU it seems not so much but then again CPU affect power when you on battery.
At the very least maybe we could show it immediately for a file, but for folder ask a question

**Comment by vovkkk** [comment]
@aziz I’ve done 1 and 2; let me know if there is is any problem; and if it is okay, could you please finish it? I mean 3 and release.

**Comment by vovkkk** [comment]
BTW, I’ve tried hover over text it is so annoying, esp. if using mouse for navigation open/expand; so it is hover over gutter now.

**Comment by aziz** [comment]
I tested it quickly and it works. This weekend I'll clean up the UI and add docs. It just needs a little bit of polish. 
This is amazing work. Thanks
