### ISSUE TITLE
Avoid loosing focus on FileBrowser tab when opening a file

### ISSUE THREAD

**Issue by Wramberg** [aziz/SublimeFileBrowser#132]
Hey,
Great plugin - I've configured two shortcuts: 
- One for closing the FileBrowser tab whenever I open a file
- One for keeping the FileBrowser tab open whenever I open a file (so I can open multiple files)

The latter keeps loosing focus to the files I'm opening though - Is there a way to avoid this maybe ?

**Comment by vovkkk** [comment]
You can select multiple files with Sublime Text multiple cursors or by marking them with <kbd>m</kbd> or <kbd>shift</kbd>+<kbd>↑</kbd>/<kbd>↓</kbd> and then open all marked/selected files.

Also you can preview file with <kbd>shift</kbd>+<kbd>enter</kbd>: focus will remain in browser and preview always take file under the first selection, so you can decide which file to mark or skip.
