### ISSUE TITLE
Why does not the tab take the look of my color scheme?

### ISSUE THREAD

**Issue by mrwnmonm** [aziz/SublimeFileBrowser#136]
I use a [custom](https://gist.github.com/mrwnmonm/d1ff821b047cc56228cc223528d4d01a) color scheme, but it doesn't change the FileBrowser tab look.    
I know the Readme refer to a color scheme file to be edited to modify the look, but i want to keep my current color scheme, and just make the files tab looks the same.  
How i could do that?
![img](http://i.imgur.com/dC7O2lY.png)

**Comment by vovkkk** [comment]
Readme refers to setting a desirable value in settings file, that’s how you do it, just add color_scheme to SFB user settings file

![2017-04-09_18-20-59](https://cloud.githubusercontent.com/assets/1975298/24836855/64f7afa6-1d51-11e7-98fe-89ae603cc064.png)
