### ISSUE TITLE
Can't make "single column" layout the default

### ISSUE THREAD

**Issue by mrwnmonm** [aziz/SublimeFileBrowser#137]
It always opens files in another two columns layout, how to stop that?

**Comment by vovkkk** [comment]
You can press <kbd>⌘+enter</kbd> or <kbd>ctrl+enter</kbd> or rebind it to <kbd>enter</kbd> in user keybindings file adding:

```js
  {
      "keys": ["enter"],
      "command": "dired_select",
      "args": { "new_view": true },
      "context": [
        { "key": "selector", "operator": "equal", "operand": "text.dired" },
        { "key": "setting.dired_rename_mode", "operand": false }
      ]
}
```

**Comment by mrwnmonm** [comment]
Thanks, works very well.
Can i do this with double click?

**Comment by vovkkk** [comment]
You can create your own plugin with unique command which would call select without other_group argument like this https://github.com/aziz/SublimeFileBrowser/blob/master/dired.py#L808-L830
and bind double click to this new command in `Packages/User/Default.sublime-mousemap` like this https://github.com/aziz/SublimeFileBrowser/blob/master/Default.sublime-mousemap

BTW, new_view argument in my prev message is not needed, remove it if do not want to open each folder in separate view.
