### ISSUE TITLE
watchdog module is not importable

### ISSUE THREAD

**Issue by Chovin** [aziz/SublimeFileBrowser#139]
### Got this error:

    error: FileBrowser:

    watchdog module is not importable, hence we cannot know about changes on file system, and auto-refresh will not work.

    Despite that, FileBrowser is fully usable without auto-refresh, you can just ignore this message and manually refresh view with r key.

    But if you want working auto-refresh:
     • if you install manually, then look at Readme how to install it,
     • if you install via Package Control, report an issue.

but I see that watchdog was installed:
```Package Control: The dependency 'watchdog' is not currently installed; installing...
Package Control: The dependency 'watchdog' has successfully been installed or updated
```

and I can import it just fine:
```
>>> import watchdog
>>> dir(watchdog)
['__doc__', '__initializing__', '__loader__', '__name__', '__package__', '__path__']
```

**Comment by vovkkk** [comment]
Does error persist after restarting Sublime Text?

**Comment by Chovin** [comment]
didn't, but after a few days it just worked. Something wonky must have happened.

Sorry!
