### ISSUE TITLE
Constant Auto-refreshing

### ISSUE THREAD

**Issue by zackshackleton** [aziz/SublimeFileBrowser#147]
When I open the file browser in a larger project, it constantly refreshes. I have noticed when I am at the top of the list, the problem doesn't appear. When the selection line causes the view to scroll, the auto refresh starts back up. This appears even when `{ "dired_autorefresh": false }` is in sublime's settings.

**Comment by tonatiuh** [comment]
Same issue here.

**Comment by tyabele** [comment]
Having the same issue. Mostly its the "expanding" a nested directory and then scrolling. Anyone have any insight?

**Comment by ksarunas** [comment]
Is there any estimate when a new version with this fix is going to be released? This auto refreshing issue is so annoying..

**Comment by zackshackleton** [comment]
@ksarunas If you install it manually instead of Package Control, it contains the fix.

**Comment by ksarunas** [comment]
@zackshackleton thanks for a suggestion, don't know why I did not think of that. Works great now. Anyways, would be nice if this fix was on Package Control too!
