### ISSUE TITLE
Hide Header Settings

### ISSUE THREAD

**Issue by aziz** [aziz/SublimeFileBrowser#61]
The header is not that useful and visible (specially when using FB as a sidebar), it would be cool to be able to hide it through settings.

**Comment by vovkkk** [comment]
I would even suggest to hide it by default.
The only reason why I like header is that it show full path (sometimes it’s useful for me), so maybe also add another option to show full path in tab title, and thus in window title if tab is focused.

**Comment by aziz** [comment]
:+1:

**Comment by aziz** [comment]
When the header is hidden, going to Rename Mode is not that obvious, we need to find a way to make it more clear that we're in rename mode. 
My idea is to replace `⠤` with `[RENAME MODE]` and highlight in different color.

**Comment by aziz** [comment]
Another challenge is  to make sure that hiding both `⠤`  and the header does not happen!

**Comment by vovkkk** [comment]
Though there might be no `⠤` we can just add line `[RENAME MODE]` on top if no header and remove on commit.

I cannot do it today, so… either tomorrow or you :smile:

**Comment by aziz** [comment]
Not today, but I'll continue working on it. We need to think about the design a little bit. I need to sleep!

**Comment by vovkkk** [comment]
@aziz look at separate branch https://github.com/aziz/SublimeFileBrowser/commit/6d06b6295c9db6fcc439d88767c762e9b18c6ee2
Just add `[RENAME MODE]` on top, and we don’t need to even care about removing since after commit view will be refreshed.

So if you approve, I’m ready to release.

**Comment by aziz** [comment]
@vovkkk  sorry I was working on it and implemented it in a different way. my commit is not that clean and contains other fixes as well, but hopefully you'll figure it out.

**Comment by aziz** [comment]
@vovkkk  here is a small todo list I'm working towards: 

- [ ] BUG: move to eof => cursor position is wrong
- [ ] BUG: unmark does not work in nested directories
- [ ] BUG: continue refresh after plugin_loaded to highlight git changes
- [ ] IMPROVEMENT: F1 on a file from project should open the project root, but expand to the file and select it.
- [ ] IMPROVEMENT: auto complete path should not use a view, use a quick panel instead
- [ ] FEATURE: file action commands using quick panel, cause you forget shortcuts, and it's easier to remember just one
- [ ] FEATURE: remember open state for folders, write them to settings.
- [ ] FEATURE: listen to disk changes (or listen sublime change events and update sidebar)
- [ ] FEATURE: add columns for date_created/size/
- [ ] FEATURE: automatic number/time/date generator when renaming myfile-${n}-${d}-${t}.ext
- [ ] FEATURE: copy/paste
- [ ] FEATURE: match other view color scheme?

**Comment by aziz** [comment]
let me know if you've got time and want to work on any of them, so that we can organize ourselves and do not work on the same thing together.

**Comment by vovkkk** [comment]
Unfortunatelly, not much time currently, but I can try fix today BUG: unmark does not work in nested directories.



> sorry I was working on it and implemented it in a different way

The view may have no item.parent_dir, I dunno maybe it would be even better to not touch view at all if no header, but change tab title (name of view).

**Comment by aziz** [comment]
> The view may have no item.parent_dir, I dunno maybe it would be even better to not touch view at all if > no header, but change tab title (name of view).

Here is what I think, if you have header we update the header, if you have parent_dir element but no header we update the parent_dir and if you don't have any of those elements then you're a purist and should look at the status bar to find the mode change, no cookie for you.

**Comment by vovkkk** [comment]
But then if you’re purist you could hide statusbar :smile: but tabs and window title could be hidden in fullscreen, so yeah let’s keep it as it is especially since double dot is there by default.

Mark/unmark is done I think, commited into master.
