### ISSUE TITLE
ST3 Jump Quick Panel jumps not working

### ISSUE THREAD

**Issue by calvinchoy** [aziz/SublimeFileBrowser#66]
Hi,

Not sure if I forgot something. I installed the package using the package installer. After adding some jump points if I want to jump using the jump panel it says it was not able to jump to that location and asks me whether I want to delete the jump point.

Using the brow jump list it works correctly.

Am I missing anything? Thanks

**Comment by V1q** [comment]
I have the same issue.
For the same jump point:
- "dired_jump_list" command works, and can jump to location by pressing enter
- "dired_jump" says it was not able to jump to the location.

**Comment by aziz** [comment]
Please check the console and see if there's any error there. I would be helpful to check your user settings cause the jump point are stored there. It'd be great if you post more info here

**Comment by calvinchoy** [comment]
I checked the console already but no error outputs on assigning and calling jump points from the quick panel.

With regard to the settings, I used the default settings. I didn't edit anything. Installed using package manager, opened a file browser as left panel and tested the jump point feature.

Will see if I can find some more info for this bug.

**Comment by aziz** [comment]
All the jump points you set are saved in `User/dired.sublime-settings` that's why I'm asking to check that file.

**Comment by V1q** [comment]
I found source of the problem, if I change
```
"dired_jump_points":
	{
		"AMB_trunk_fw": "P:\\projects\\test"
	}
```
to

```
"dired_jump_points":
	{
		"AMB_trunk_fw": "P:\\projects\\test\\"
	}
```
it starts working

**Comment by calvinchoy** [comment]
I make a TEST jump point, here is what is stored in `User/dired.sublime-settings`:

    {
	"color_scheme": "Packages/FileBrowser/dired.hidden-tmTheme",
	"dired_confirm_send2trash": true,
	"dired_header": false,
	"dired_hidden_files_patterns":
	[
		".*"
	],
	"dired_hijack_new_window": false,
	"dired_jump_points":
	{
		"TEST": "/Users/Karubin/Sites/dev.asqa.com"
	},
	"dired_reuse_view": true,
	"dired_show_full_path": false,
	"dired_show_hidden_files": true,
	"dired_show_parent": true,
	"drag_text": false,
	"draw_indent_guides": false,
	"fold_buttons": false,
	"git_path": "/usr/bin/git",
	"highlight_line": true,
	"line_numbers": false,
	"margin": 0,
	"rulers":
	[
	],
	"scroll_past_end": false,
	"single_pane": true,
	"spell_check": false,
	"tab_size": 3,
	"word_wrap": false
    }

I use `p` to pull out the quick panel and select this jump point. I received the following alert:

    Can't jump to 'TEST → /Users/Karubin/Sites/dev.asqa.com'.

    Remove that jump point?`

**Comment by aziz** [comment]
I think I found the bug. Yes it is missing slashes/backslashes at the end of the path.

**Comment by calvinchoy** [comment]
I can confirm that the backslash fixes the problem.

**Comment by vovkkk** [comment]
It is feature!! just kidding; my fault, I’m sorry.

It fixed in master two days ago, but there is another problem with tab title (which fixed in x-63 branch), @aziz if you have time today, please, go ahead and release fix, otherwise I’ll do it tomorrow

**Comment by calvinchoy** [comment]
Hah,

Thanks guy, great plugin!

**Comment by aziz** [comment]
It's 12 at midnight here and I need to work tomorrow. since we've found a solution for the guys to fix it temporarily I guess it's ok to wait for you to push all your changes.

**Comment by V1q** [comment]
Thanks for quick reply and great plugin :)
