### ISSUE TITLE
Deleting expanded empty directory fails with error message

### ISSUE THREAD

**Issue by theArchonius** [aziz/SublimeFileBrowser#67]
Suppose I have found a unwanted empty directory called `templates` by expanding elements of the file tree within SublimeFileBrowser.
Deleting it will prompt a dialog with the message  `Delete templates/	<empty>?` and if I accept it, the following error occurs and the directory is not deleted: 

    Some files couldn’t be deleted: 
    
    [Errno 2] No such file or directory:	templates/	<empty>"

**Comment by vovkkk** [comment]
fixed in #63 
for now you can hit <kbd>enter</kbd> twice and then delete.
