### ISSUE TITLE
Delete empty directory

### ISSUE THREAD

**Issue by manuelmeurer** [aziz/SublimeFileBrowser#69]
When I try to delete an empty directory with "D", I first get "Delete my/directory <empty>?", and once I click "OK", I get "Some files couldn't be deleted: [Errno 2] No such file or directory:my/directory <empty>".
Is there some other way to delete an empty directory?

**Comment by aziz** [comment]
It does not happen on master for me. We've changed quite a lot since last release and preparing to do a major release soon. Could you checkout the master and see if it happens. 
BTW, `D` now deletes to trash, and permanent delete is `now alt+shift+d`

**Comment by vovkkk** [comment]
FWIW, Python in ST2 on Windows is buggy (note trailing whitspaces and os.sep)
```
>>> os.path.isdir('C:\\Users\\vova\\AppData\\Roaming\\Sublime Text 2\\Packages\\User\\d  \\')
True
>>> os.path.isdir('C:\\Users\\vova\\AppData\\Roaming\\Sublime Text 2\\Packages\\User\\d  ')
False
>>> os.path.isdir('C:\\Users\\vova\\AppData\\Roaming\\Sublime Text 2\\Packages\\User\\Package Control.cache')
True
```
Yea, so if you got trailing whitespace then expect bugs all over (esp. taking into account that `os.listdir` returns without trailing `os.sep`)

**Comment by manuelmeurer** [comment]
Ok cool, I'll wait for the next release then and test it again then. I also noticed mouse actions don't work, doubleclicking a file or folder doesn't open it. Might that also be fixed in the next release?

**Comment by aziz** [comment]
Yes! Double click to open file or folders is added.

**Comment by aziz** [comment]
@manuelmeurer could you check this bug again, We've release the new version.

**Comment by manuelmeurer** [comment]
Works now! :+1: A small improvement could be to let the cursor jump to the item above the deleted folder if possible, not to the top of the whole list.

**Comment by aziz** [comment]
> A small improvement could be to let the cursor jump to the item above the deleted folder if possible, not to the top of the whole list.

Added it to my list.
