### ISSUE TITLE
Open automatically

### ISSUE THREAD

**Issue by manuelmeurer** [aziz/SublimeFileBrowser#70]
Maybe I'm missing something obvious, but how can I configure File Browser to open automatically when I open a project? I set up the "f1" keybinding as detailed in the readme, but it would be nice to get this to open automatically.
Cheers for this great project! :+1:

**Comment by vovkkk** [comment]
I don’t understand this request. ST2 on Windows restores all views (including SFB’s).

Is it maybe some bug in ST3?

**Comment by manuelmeurer** [comment]
Yeah, now it works for me as well (ST3 3083 on Mac). Maybe a bug in an earlier version of ST...
