### ISSUE TITLE
FileBrowser blocking double click in sublime tabs (looks like any text tabs)

### ISSUE THREAD

**Issue by sergey-kucher** [aziz/SublimeFileBrowser#74]
Hi, guys!

After last update, FileBrowser blocking double click on words in other tabs. So it's preventing "select whole word" operation.

And last features is pretty awesome by the way

**Comment by sergey-kucher** [comment]
Tested in ST3 on linux

**Comment by vovkkk** [comment]
Works for me. Did you restart Sublime? any errors in console?

**Comment by sergey-kucher** [comment]
No errors in console. I didn't restart Sublime, but disable/enable SFB didn't helps. I'll restart Sublime and tell you about results.

**Comment by sergey-kucher** [comment]
Unfortunately nothing changes after Sublime restart. Moreover the same situation on another machine (same - ST3, Linux Mint)

**Comment by sergey-kucher** [comment]
I don't know why, but now all works fine for me.
Looks like I can close issue.
