### ISSUE TITLE
jump points based on current project

### ISSUE THREAD

**Issue by calvinchoy** [aziz/SublimeFileBrowser#76]
Is it possible to make the jump point list project dependent? As for now, the jump point list global in sublime text.

Thanks

**Comment by vovkkk** [comment]
Well, the answer is yes, it is probably possible, but why? project has folders, so normally you get list of them when call FileBrowser.
If you use ST3 you can add folder from within FileBrowser into project <kbd>f</kbd>, on ST2 you have to drag&drop folder(s) from Explorer/Finder onto ST.

Project dependent jump points would add too much complexity with small benefit, imho.

**Comment by calvinchoy** [comment]
Then I probably misunderstand the purpose of jump points. I thought it was a quick way to jump to specific locations in a project instead of hard bookmarks in the whole filesystem. I understand that the benefit is small, it was more of a convenient if it was available. I usually just load the project folder instead of separate folders, some folder have a deep folder structure due to frameworks convenient so thought it would be great to set jump points, but as you can see the list get pretty long and polluted overtime and there are chances that I accidently jump outside the project folders.

-- 
Calvin Choy



On 22 Mar 2015 at 00:26:44, Vova Kolobok (notifications@github.com) wrote:

Well, the answer is yes, it is probably possible, but why? project has folders, so normally you get list of them when call FileBrowser.
If you use ST3 you can add folder from within FileBrowser into project f, on ST2 you have to drag&drop folder(s) from Explorer/Finder onto ST.

Project dependent jump points would add too much complexity with small benefit, imho.

**Comment by vovkkk** [comment]
You can add subfolders into project as you like, e.g. let’s say you got 

```
▾ app\
   ▸ libs\
```
you can add both into project as roots; and then if add `"project": true` argument to keybinding you’ll always get list of project folders.

**Comment by calvinchoy** [comment]
Cool, I will try that out :) Thanks!
