### ISSUE TITLE
remove duplicate command after copy-paste release

### ISSUE THREAD

**Issue by MrAtiebatie** [aziz/SublimeFileBrowser#77]
Is there any chance you can make a duplicate command? It's a feature in the SidebarEnhancements plugin which I use very often. Would love to see that as a command in the sidebar too :)

Awesome plugin furthermore!

MrAtiebatie

**Comment by vovkkk** [comment]
It is already there, look at default keybindings file for commented lines, you can copy them into user file and uncomment, but it was added before tree view, so it might work not exactly as you may expect.

Though this command inevitably is going to be deprecated in favour of copy-paste, soon™

**Comment by MrAtiebatie** [comment]
Oh my bad I was looking at the help file (shift+?). Any idea when the copy-paste feature is going to be implemented?

**Comment by vovkkk** [comment]
It is now, but not released, see #64
