### ISSUE TITLE
Proposal: Disable Vintageous

### ISSUE THREAD

**Issue by andradei** [aziz/SublimeFileBrowser#80]
The [Vintageous](https://github.com/guillermooo/Vintageous) plugin causes control problems when used in conjunction with SublimeFileBrowser.

Is it possible to add an option where this plugin can _disable_ Vintageous while SublimeFileBrowser's windows is active (and _enable_ it back when it loses focus)?

**Comment by vovkkk** [comment]
dup #4 

ref https://github.com/guillermooo/Vintageous/issues/820

**Comment by andradei** [comment]
It works, thanks!
