### ISSUE TITLE
Sidebar width

### ISSUE THREAD

**Issue by LeusMaximus** [aziz/SublimeFileBrowser#89]
Can we change default sidebar width?

**Comment by vovkkk** [comment]
Do you mean as a setting? Sure, it’d be possible. I’ll do new release this weekend.

**Comment by LeusMaximus** [comment]
Yes. Because every time we must to change the width manually.
And thanks for package. It's very comfortable.

**Comment by vovkkk** [comment]
The width is being set as percent, currently it is 0.3, i.e. 30% of window width.
To make it clear, do you mean width setting in percent or pixels? because if percent, then it’s very simple, if pixels it’s not so simple, but still possible.
More over, we could even support both, i.e. treat float (e.g. 0.2) as percent and treat int (e.g. 100) as pixels. What you think?

**Comment by LeusMaximus** [comment]
I thik it would be great if you could even support both. But if pixels it’s not so simple, maybe it makes no sense to spend time on it, if pixels is not needed for the majority of users.

**Comment by vovkkk** [comment]
I meant that pixels need calculation, while float could be set directly; all in all both things pretty simple.

**Comment by vovkkk** [comment]
Please test, let me know any problem https://github.com/aziz/SublimeFileBrowser/tree/x-perfomance-matter
Release this weekend.

**Comment by LeusMaximus** [comment]
I tested. All is well. Thanks.

**Comment by brokenalarms** [comment]
Unless I'm missing something, could you please add this to the documentation? I only found this feature existed through going to lodge an issue for it and finding this post, and I could then only find the variable dired_width by reading the source code directly. Thanks!

**Comment by vovkkk** [comment]
It is documented in [default settings file](https://github.com/aziz/SublimeFileBrowser/blob/master/dired.sublime-settings#L58-L62).

**Comment by brokenalarms** [comment]
Ah, I see, thanks ...soo perhaps you could mention in the documentation that there are also other undocumented settings, which can be reviewed in the default settings file? ;)

Seriously, the only one mentioned is VCS integration and if looking for a feature I would first search the documentation. Maybe I've just been lucky with not so far needing to review any default settings files for packages  "just to check if such a feature in my head exists" but I think having to do that and mentally mapping a potential key to a desired feature carries a higher overhead then just being present in the front page feature list - just seems more hidden than everything else in this package. I only mean this constructively and thank you for a great product!
