### ISSUE TITLE
Unable to commit renaming changes

### ISSUE THREAD

**Issue by rgorel** [aziz/SublimeFileBrowser#90]
Steps to reproduce:

1. Open FileBrowser
2. Put the cursor on some file
2. Hit Shift+R
3. Change file name
4. Hit enter

Expected behavior: Go from rename to normal mode, the file has the updated name

Actual behavior: An alert with the text 'You cannot add or remove lines' pops up; after closing the alert, FileBrowser stays in rename mode. Hitting escape cancels all changes.

Version: 0.7.2

**Comment by vovkkk** [comment]
As temporary workaround disable header and/or parent double dot.
I’ll fix it today.
