### ISSUE TITLE
Create a file and immediately open it

### ISSUE THREAD

**Issue by LeusMaximus** [aziz/SublimeFileBrowser#93]
Is it possible immediately open file when we create it with 'cf' command? For example to make the cursor moved to the new file in the sidebar.

**Comment by vovkkk** [comment]
Moving cursor hopefully will be easy to add after refactoring in the middle of which I am now (expecting finish it in a week or two). Now it is not easy.

Just open file/folder should be easy to do right now with <kbd>ctrl+enter</kbd>, I’ll release tomorrow this feature with couple of fixes for regressions found while refactoring.
