### ISSUE TITLE
Make Sidebar Use the Current Theme

### ISSUE THREAD

**Issue by nfarrar** [aziz/SublimeFileBrowser#95]
The readme includes instructions on setting a custom, hardcoded theme for dired. Is there anyway to make it use the current theme instead?

**Comment by vovkkk** [comment]
It shall use whatever scheme you set in user settings file, e.g. `"color_scheme": "Packages/Color Scheme - Default/LAZY.tmTheme"`

The reason, why readme advises to copy bundled one and modifying it, is that any other scheme most probably won’t contain FileBrowser-specific scopes, unless you add them youself.
